runtime: nodejs18

env_variables:
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"

instance_class: F2

handlers:
  - url: /.*
    secure: always
    script: auto

resources:
  cpu: 2
  memory_gb: 1
  disk_size_gb: 10